name: Release
on:
  push:

jobs:
  create-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Tag
        id: tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Create Release draft
        run: gh release create -d -t  "Realse ${{ steps.tag.outputs.tag }}" ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  release:
    needs:
      - create-draft
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            package: "*.rpm *.deb"
          - os: windows-latest
            package: "*.msi"
          - os: macos-latest
            package: "*.dmg *.pkg"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Package
        run: ./gradlew jpackage
      - name: List files
        working-directory: build/jpackage
        run: ls
      - name: Upload files
        working-directory: build/jpackage
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release upload "${{ github.ref }}" ${{ matrix.package }}